-- MySQL Script generated by MySQL Workbench
-- Tue Jan 28 13:51:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vanilla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vanilla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vanilla` DEFAULT CHARACTER SET utf8 ;
USE `vanilla` ;

-- -----------------------------------------------------
-- Table `vanilla`.`comida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`comida` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`comida` (
  `id_comida` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_comida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`perfil_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`perfil_cliente` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`perfil_cliente` (
  `id_perfil` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `nivel` INT(45) NULL,
  `avatar` INT NULL,
  `puntos` INT NULL,
  `comida_id_comida` INT NOT NULL,
  PRIMARY KEY (`id_perfil`, `comida_id_comida`),
  INDEX `fk_perfil_cliente_comida1_idx` (`comida_id_comida` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_cliente_comida1`
    FOREIGN KEY (`comida_id_comida`)
    REFERENCES `vanilla`.`comida` (`id_comida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`cliente` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `fecha_nacimiento` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `contra` VARCHAR(45) NULL,
  `perfil_cliente_id_perfil` INT NOT NULL,
  PRIMARY KEY (`id_cliente`, `perfil_cliente_id_perfil`),
  INDEX `fk_cliente_perfil_cliente_idx` (`perfil_cliente_id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_perfil_cliente`
    FOREIGN KEY (`perfil_cliente_id_perfil`)
    REFERENCES `vanilla`.`perfil_cliente` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`avatar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`avatar` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`avatar` (
  `id_avatar` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `disponibilidad` INT(45) NULL,
  PRIMARY KEY (`id_avatar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`perfil_cliente_has_avatar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`perfil_cliente_has_avatar` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`perfil_cliente_has_avatar` (
  `perfil_cliente_id_perfil` INT NOT NULL AUTO_INCREMENT,
  `perfil_cliente_comida_id_comida` INT NOT NULL,
  `avatar_id_avatar` INT NOT NULL,
  PRIMARY KEY (`perfil_cliente_id_perfil`, `perfil_cliente_comida_id_comida`, `avatar_id_avatar`),
  INDEX `fk_perfil_cliente_has_avatar_avatar1_idx` (`avatar_id_avatar` ASC) VISIBLE,
  INDEX `fk_perfil_cliente_has_avatar_perfil_cliente1_idx` (`perfil_cliente_id_perfil` ASC, `perfil_cliente_comida_id_comida` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_cliente_has_avatar_perfil_cliente1`
    FOREIGN KEY (`perfil_cliente_id_perfil` , `perfil_cliente_comida_id_comida`)
    REFERENCES `vanilla`.`perfil_cliente` (`id_perfil` , `comida_id_comida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perfil_cliente_has_avatar_avatar1`
    FOREIGN KEY (`avatar_id_avatar`)
    REFERENCES `vanilla`.`avatar` (`id_avatar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`admin` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`admin` (
  `id_admin` INT NOT NULL AUTO_INCREMENT,
  `registro` INT(45) NULL,
  `contra` VARCHAR(45) NULL,
  PRIMARY KEY (`id_admin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`perfil_negocio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`perfil_negocio` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`perfil_negocio` (
  `id_perfil` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `logo` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `ubicacion` VARCHAR(45) NULL,
  `boton_general` VARCHAR(45) NULL,
  `tamaño` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `calificacion` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  `rango_precio` VARCHAR(45) NULL,
  `concepto` VARCHAR(45) NULL,
  `verificacion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_perfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`negocio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`negocio` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`negocio` (
  `id_negocio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `fecha_nacimiento` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `contra` VARCHAR(45) NULL,
  `perfil_negocio_id_perfil` INT NOT NULL,
  PRIMARY KEY (`id_negocio`, `perfil_negocio_id_perfil`),
  INDEX `fk_negocio_perfil_negocio1_idx` (`perfil_negocio_id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_negocio_perfil_negocio1`
    FOREIGN KEY (`perfil_negocio_id_perfil`)
    REFERENCES `vanilla`.`perfil_negocio` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`publicidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`publicidad` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`publicidad` (
  `id_publicidad` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `perfil_negocio_id_perfil` INT NOT NULL,
  `imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`id_publicidad`, `perfil_negocio_id_perfil`),
  INDEX `fk_publicidad_perfil_negocio1_idx` (`perfil_negocio_id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_publicidad_perfil_negocio1`
    FOREIGN KEY (`perfil_negocio_id_perfil`)
    REFERENCES `vanilla`.`perfil_negocio` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`promocion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`promocion` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`promocion` (
  `id_promocion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `imagen` VARCHAR(45) NULL,
  `perfil_negocio_id_perfil` INT NOT NULL,
  PRIMARY KEY (`id_promocion`, `perfil_negocio_id_perfil`),
  INDEX `fk_promocion_perfil_negocio1_idx` (`perfil_negocio_id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_promocion_perfil_negocio1`
    FOREIGN KEY (`perfil_negocio_id_perfil`)
    REFERENCES `vanilla`.`perfil_negocio` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`menu` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`menu` (
  `id_menu` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `imagen` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `grupo` VARCHAR(45) NULL,
  `perfil_negocio_id_perfil` INT NOT NULL,
  PRIMARY KEY (`id_menu`, `perfil_negocio_id_perfil`),
  INDEX `fk_menu_perfil_negocio1_idx` (`perfil_negocio_id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_menu_perfil_negocio1`
    FOREIGN KEY (`perfil_negocio_id_perfil`)
    REFERENCES `vanilla`.`perfil_negocio` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`forma_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`forma_pago` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`forma_pago` (
  `id_pago` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `perfil_negocio_id_perfil` INT NOT NULL,
  PRIMARY KEY (`id_pago`, `perfil_negocio_id_perfil`),
  INDEX `fk_forma_pago_perfil_negocio1_idx` (`perfil_negocio_id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_forma_pago_perfil_negocio1`
    FOREIGN KEY (`perfil_negocio_id_perfil`)
    REFERENCES `vanilla`.`perfil_negocio` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`horario` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`horario` (
  `id_horario` INT NOT NULL AUTO_INCREMENT,
  `dia_semana` VARCHAR(45) NULL,
  `hora_inicio` VARCHAR(45) NULL,
  `hora_fin` VARCHAR(45) NULL,
  `perfil_negocio_id_perfil` INT NOT NULL,
  PRIMARY KEY (`id_horario`, `perfil_negocio_id_perfil`),
  INDEX `fk_horario_perfil_negocio1_idx` (`perfil_negocio_id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_horario_perfil_negocio1`
    FOREIGN KEY (`perfil_negocio_id_perfil`)
    REFERENCES `vanilla`.`perfil_negocio` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`servicio` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`servicio` (
  `id_servicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_servicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`perfil_negocio_has_servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`perfil_negocio_has_servicio` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`perfil_negocio_has_servicio` (
  `servicio_id_servicio` INT NOT NULL AUTO_INCREMENT,
  `perfil_negocio_id_perfil` INT NOT NULL,
  PRIMARY KEY (`servicio_id_servicio`, `perfil_negocio_id_perfil`),
  INDEX `fk_servicio_has_perfil_negocio_perfil_negocio1_idx` (`perfil_negocio_id_perfil` ASC) VISIBLE,
  INDEX `fk_servicio_has_perfil_negocio_servicio1_idx` (`servicio_id_servicio` ASC) VISIBLE,
  CONSTRAINT `fk_servicio_has_perfil_negocio_servicio1`
    FOREIGN KEY (`servicio_id_servicio`)
    REFERENCES `vanilla`.`servicio` (`id_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicio_has_perfil_negocio_perfil_negocio1`
    FOREIGN KEY (`perfil_negocio_id_perfil`)
    REFERENCES `vanilla`.`perfil_negocio` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`reservacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`reservacion` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`reservacion` (
  `cliente_id_cliente` INT NOT NULL AUTO_INCREMENT,
  `cliente_perfil_cliente_id_perfil` INT NOT NULL,
  `perfil_negocio_id_perfil` INT NOT NULL,
  `hora` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `numero_personas` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `comentario` VARCHAR(45) NULL,
  `fecha_hora` VARCHAR(45) NULL,
  PRIMARY KEY (`cliente_id_cliente`, `cliente_perfil_cliente_id_perfil`, `perfil_negocio_id_perfil`),
  INDEX `fk_cliente_has_perfil_negocio_perfil_negocio1_idx` (`perfil_negocio_id_perfil` ASC) VISIBLE,
  INDEX `fk_cliente_has_perfil_negocio_cliente1_idx` (`cliente_id_cliente` ASC, `cliente_perfil_cliente_id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_perfil_negocio_cliente1`
    FOREIGN KEY (`cliente_id_cliente` , `cliente_perfil_cliente_id_perfil`)
    REFERENCES `vanilla`.`cliente` (`id_cliente` , `perfil_cliente_id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_perfil_negocio_perfil_negocio1`
    FOREIGN KEY (`perfil_negocio_id_perfil`)
    REFERENCES `vanilla`.`perfil_negocio` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`lista_negocio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`lista_negocio` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`lista_negocio` (
  `cliente_id_cliente` INT NOT NULL,
  `id_lista_negocio` INT NOT NULL,
  `perfil_negocio_id_perfil` INT NOT NULL,
  PRIMARY KEY (`cliente_id_cliente`, `id_lista_negocio`, `perfil_negocio_id_perfil`),
  INDEX `fk_cliente_has_perfil_negocio1_perfil_negocio1_idx` (`perfil_negocio_id_perfil` ASC) VISIBLE,
  INDEX `fk_cliente_has_perfil_negocio1_cliente1_idx` (`cliente_id_cliente` ASC, `id_lista_negocio` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_perfil_negocio1_cliente1`
    FOREIGN KEY (`cliente_id_cliente` , `id_lista_negocio`)
    REFERENCES `vanilla`.`cliente` (`id_cliente` , `perfil_cliente_id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_perfil_negocio1_perfil_negocio1`
    FOREIGN KEY (`perfil_negocio_id_perfil`)
    REFERENCES `vanilla`.`perfil_negocio` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`cupon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`cupon` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`cupon` (
  `perfil_negocio_id_perfil` INT NOT NULL AUTO_INCREMENT,
  `cliente_id_cliente` INT NOT NULL,
  `id_cupon` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`perfil_negocio_id_perfil`, `cliente_id_cliente`, `id_cupon`),
  INDEX `fk_perfil_negocio_has_cliente_cliente1_idx` (`cliente_id_cliente` ASC, `id_cupon` ASC) VISIBLE,
  INDEX `fk_perfil_negocio_has_cliente_perfil_negocio1_idx` (`perfil_negocio_id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_negocio_has_cliente_perfil_negocio1`
    FOREIGN KEY (`perfil_negocio_id_perfil`)
    REFERENCES `vanilla`.`perfil_negocio` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perfil_negocio_has_cliente_cliente1`
    FOREIGN KEY (`cliente_id_cliente` , `id_cupon`)
    REFERENCES `vanilla`.`cliente` (`id_cliente` , `perfil_cliente_id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`buscar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`buscar` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`buscar` (
  `cliente_id_cliente` INT NOT NULL AUTO_INCREMENT,
  `cliente_perfil_cliente_id_perfil` INT NOT NULL,
  `perfil_negocio_id_perfil` INT NOT NULL,
  PRIMARY KEY (`cliente_id_cliente`, `cliente_perfil_cliente_id_perfil`, `perfil_negocio_id_perfil`),
  INDEX `fk_cliente_has_perfil_negocio_perfil_negocio2_idx` (`perfil_negocio_id_perfil` ASC) VISIBLE,
  INDEX `fk_cliente_has_perfil_negocio_cliente2_idx` (`cliente_id_cliente` ASC, `cliente_perfil_cliente_id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_perfil_negocio_cliente2`
    FOREIGN KEY (`cliente_id_cliente` , `cliente_perfil_cliente_id_perfil`)
    REFERENCES `vanilla`.`cliente` (`id_cliente` , `perfil_cliente_id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_perfil_negocio_perfil_negocio2`
    FOREIGN KEY (`perfil_negocio_id_perfil`)
    REFERENCES `vanilla`.`perfil_negocio` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`calificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`calificacion` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`calificacion` (
  `cliente_id_cliente` INT NOT NULL,
  `cliente_perfil_cliente_id_perfil` INT NOT NULL,
  `perfil_negocio_id_perfil` INT NOT NULL,
  `calificacion` INT NULL,
  PRIMARY KEY (`cliente_id_cliente`, `cliente_perfil_cliente_id_perfil`, `perfil_negocio_id_perfil`),
  INDEX `fk_cliente_has_perfil_negocio_perfil_negocio3_idx` (`perfil_negocio_id_perfil` ASC) VISIBLE,
  INDEX `fk_cliente_has_perfil_negocio_cliente3_idx` (`cliente_id_cliente` ASC, `cliente_perfil_cliente_id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_perfil_negocio_cliente3`
    FOREIGN KEY (`cliente_id_cliente` , `cliente_perfil_cliente_id_perfil`)
    REFERENCES `vanilla`.`cliente` (`id_cliente` , `perfil_cliente_id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_perfil_negocio_perfil_negocio3`
    FOREIGN KEY (`perfil_negocio_id_perfil`)
    REFERENCES `vanilla`.`perfil_negocio` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`comida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`comida` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`comida` (
  `id_comida` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_comida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`perfil_negocio_has_comida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`perfil_negocio_has_comida` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`perfil_negocio_has_comida` (
  `perfil_negocio_id_perfil` INT NOT NULL AUTO_INCREMENT,
  `comida_idcomida` INT NOT NULL,
  PRIMARY KEY (`perfil_negocio_id_perfil`, `comida_idcomida`),
  INDEX `fk_perfil_negocio_has_comida_comida1_idx` (`comida_idcomida` ASC) VISIBLE,
  INDEX `fk_perfil_negocio_has_comida_perfil_negocio1_idx` (`perfil_negocio_id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_negocio_has_comida_perfil_negocio1`
    FOREIGN KEY (`perfil_negocio_id_perfil`)
    REFERENCES `vanilla`.`perfil_negocio` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perfil_negocio_has_comida_comida1`
    FOREIGN KEY (`comida_idcomida`)
    REFERENCES `vanilla`.`comida` (`id_comida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`notificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`notificacion` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`notificacion` (
  `cliente_id_cliente` INT NOT NULL,
  `id_notificacion` INT NOT NULL,
  `perfil_negocio_id_perfil` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`cliente_id_cliente`, `id_notificacion`, `perfil_negocio_id_perfil`),
  INDEX `fk_cliente_has_perfil_negocio_perfil_negocio4_idx` (`perfil_negocio_id_perfil` ASC) VISIBLE,
  INDEX `fk_cliente_has_perfil_negocio_cliente4_idx` (`cliente_id_cliente` ASC, `id_notificacion` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_perfil_negocio_cliente4`
    FOREIGN KEY (`cliente_id_cliente` , `id_notificacion`)
    REFERENCES `vanilla`.`cliente` (`id_cliente` , `perfil_cliente_id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_perfil_negocio_perfil_negocio4`
    FOREIGN KEY (`perfil_negocio_id_perfil`)
    REFERENCES `vanilla`.`perfil_negocio` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`foto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`foto` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`foto` (
  `id_foto` INT NOT NULL,
  `perfil_negocio_id_perfil` INT NOT NULL,
  `namefile` VARCHAR(45) NULL,
  PRIMARY KEY (`id_foto`, `perfil_negocio_id_perfil`),
  INDEX `fk_foto_perfil_negocio1_idx` (`perfil_negocio_id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_foto_perfil_negocio1`
    FOREIGN KEY (`perfil_negocio_id_perfil`)
    REFERENCES `vanilla`.`perfil_negocio` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`comentario` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`comentario` (
  `cliente_id_cliente` INT NOT NULL AUTO_INCREMENT,
  `id_comentario` INT NOT NULL,
  `perfil_negocio_id_perfil` INT NOT NULL,
  `comentario` VARCHAR(45) NULL,
  `calificacion` INT NULL,
  PRIMARY KEY (`cliente_id_cliente`, `id_comentario`, `perfil_negocio_id_perfil`),
  INDEX `fk_cliente_has_perfil_negocio_perfil_negocio5_idx` (`perfil_negocio_id_perfil` ASC) VISIBLE,
  INDEX `fk_cliente_has_perfil_negocio_cliente5_idx` (`cliente_id_cliente` ASC, `id_comentario` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_perfil_negocio_cliente5`
    FOREIGN KEY (`cliente_id_cliente` , `id_comentario`)
    REFERENCES `vanilla`.`cliente` (`id_cliente` , `perfil_cliente_id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_perfil_negocio_perfil_negocio5`
    FOREIGN KEY (`perfil_negocio_id_perfil`)
    REFERENCES `vanilla`.`perfil_negocio` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanilla`.`locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vanilla`.`locations` ;

CREATE TABLE IF NOT EXISTS `vanilla`.`locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lat` FLOAT(10,6) NOT NULL,
  `lng` FLOAT(10,6) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `location_status` TINYINT(1) NULL,
  `perfil_negocio_id_perfil` INT NOT NULL,
  PRIMARY KEY (`id`, `perfil_negocio_id_perfil`),
  INDEX `fk_locations_perfil_negocio1_idx` (`perfil_negocio_id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_locations_perfil_negocio1`
    FOREIGN KEY (`perfil_negocio_id_perfil`)
    REFERENCES `vanilla`.`perfil_negocio` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
